// Generated by ts-to-zod
import { z } from "zod";

export const strapiTemplateSchema = z.object({
    background: z.string().optional(),
    description: z.string(),
    how: z.array(z.object({
        description: z.string(),
        icon: z.string(),
        title: z.string()
    })).optional(),
    image: z.string().optional(),
    output_image: z.string().optional(),
    pre_title: z.string(),
    price: z.object({
        is_strikethrough: z.number().optional().default(0),
        previous_price: z.string().optional(),
        price: z.string()
    }).optional(),
    requirements: z.object({
        description: z.string(),
        list: z.array(z.string())
    }).optional(),
    tags: z.array(z.object({
        icon: z.string(),
        text: z.string()
    })),
    title: z.string(),
    what: z.object({
        description: z.string(),
        goal: z.string()
    }).optional(),
    why: z.object({
        advantages: z.array(z.string()),
        reasons: z.array(z.object({
            description: z.string(),
            icon: z.string(),
            title: z.string()
        }))
    }).optional()
});

export const cpReqTemplateSchema = z.object({
    category_id: z.number(),
    config: z.string(),
    description: z.string().optional(),
    id: z.number(),
    name: z.string(),
    price: z.string().optional(),
    strapi: strapiTemplateSchema.optional(),
    workspace_id: z.number().optional()
});

export const planStatusSchema = z.union([z.literal("pending_review"), z.literal("draft"), z.literal("approved"), z.literal("paying")]);

export const outputModuleTouchpointsAppDesktopSchema = z.object({
    form_factor: z.literal("desktop"),
    kind: z.literal("app"),
    os: z.object({
        linux: z.string().optional(),
        macos: z.string().optional(),
        windows: z.string().optional()
    })
});

export const outputModuleTouchpointsAppSmartphoneSchema = z.object({
    form_factor: z.literal("smartphone"),
    kind: z.literal("app"),
    os: z.object({
        android: z.string().optional(),
        ios: z.string().optional()
    })
});

export const outputModuleTouchpointsAppTabletSchema = z.object({
    form_factor: z.literal("tablet"),
    kind: z.literal("app"),
    os: z.object({
        ios: z.string().optional(),
        android: z.string().optional()
    })
});

export const outputModuleTouchpointsWebDesktopSchema = z.object({
    form_factor: z.literal("desktop"),
    kind: z.literal("web"),
    os: z.object({
        linux: z.string().optional(),
        macos: z.string().optional(),
        windows: z.string().optional()
    })
});

export const outputModuleTouchpointsWebSmartphoneSchema = z.object({
    form_factor: z.literal("smartphone"),
    kind: z.literal("web"),
    os: z.object({
        android: z.string().optional(),
        ios: z.string().optional()
    })
});

export const outputModuleTouchpointsWebTabletSchema = z.object({
    form_factor: z.literal("tablet"),
    kind: z.literal("web"),
    os: z.object({
        android: z.string().optional(),
        ios: z.string().optional()
    })
});

export const outputServiceProvidersSchema = z.array(z.object({
    isOther: z.number().optional(),
    name: z.string()
}));

export const outputModuleTouchpointsSchema = z.union([outputModuleTouchpointsAppDesktopSchema, outputModuleTouchpointsAppTabletSchema, outputModuleTouchpointsAppSmartphoneSchema, outputModuleTouchpointsWebDesktopSchema, outputModuleTouchpointsWebTabletSchema, outputModuleTouchpointsWebSmartphoneSchema]);

export const outputModuleTaskAccessibilitySchema = z.object({
    description: z.string().optional(),
    id: z.string().optional(),
    kind: z.literal("accessibility"),
    title: z.string(),
    url: z.string().optional()
});

export const outputModuleTaskBugSchema = z.object({
    description: z.string().optional(),
    id: z.string().optional(),
    kind: z.literal("bug"),
    title: z.string(),
    url: z.string().optional()
});

export const outputModuleTaskExplorativeBugSchema = z.object({
    description: z.string().optional(),
    id: z.string().optional(),
    kind: z.literal("explorative-bug"),
    title: z.string(),
    url: z.string().optional()
});

export const outputModuleTaskModerateVideoSchema = z.object({
    description: z.string().optional(),
    id: z.string().optional(),
    kind: z.literal("moderate-video"),
    title: z.string(),
    url: z.string().optional()
});

export const outputModuleTaskSurveySchema = z.object({
    description: z.string().optional(),
    id: z.string().optional(),
    kind: z.literal("survey"),
    title: z.string(),
    url: z.string().optional()
});

export const outputModuleTaskVideoSchema = z.object({
    description: z.string().optional(),
    id: z.string().optional(),
    kind: z.literal("video"),
    title: z.string(),
    url: z.string().optional()
});

export const outputModuleTaskSchema = z.union([outputModuleTaskVideoSchema, outputModuleTaskBugSchema, outputModuleTaskSurveySchema, outputModuleTaskModerateVideoSchema, outputModuleTaskExplorativeBugSchema, outputModuleTaskAccessibilitySchema]);

export const moduleAdditionalTargetSchema = z.object({
    output: z.string(),
    type: z.literal("additional_target"),
    variant: z.string()
});

export const outputModuleAgeSchema = z.array(z.object({
    max: z.number(),
    min: z.number(),
    percentage: z.number()
}));

export const outputModuleBrowserSchema = z.array(z.object({
    name: z.union([z.literal("firefox"), z.literal("edge"), z.literal("chrome"), z.literal("safari")]),
    percentage: z.number()
}));

export const outputModuleGenderSchema = z.array(z.object({
    gender: z.union([z.literal("male"), z.literal("female")]),
    percentage: z.number()
}));

export const outputModuleIncomeRangeSchema = z.array(z.object({
    max: z.number(),
    min: z.number(),
    percentage: z.number()
}));

export const outputModuleLiteracySchema = z.array(z.object({
    level: z.union([z.literal("beginner"), z.literal("intermediate"), z.literal("expert")]),
    percentage: z.number()
}));

export const outputModuleLocalitySchema = z.array(z.object({
    type: z.string(),
    values: z.array(z.string())
}));

export const moduleAgeSchema = z.object({
    output: outputModuleAgeSchema,
    type: z.literal("age"),
    variant: z.string()
});

export const moduleAnnualIncomeRangeSchema = z.object({
    output: outputModuleIncomeRangeSchema,
    type: z.literal("annual_income_range"),
    variant: z.string()
});

export const moduleBankSchema = z.object({
    output: outputServiceProvidersSchema,
    type: z.literal("bank"),
    variant: z.string()
});

export const moduleBrowserSchema = z.object({
    output: outputModuleBrowserSchema,
    type: z.literal("browser"),
    variant: z.string()
});

export const moduleDateSchema = z.object({
    output: z.object({
        start: z.string()
    }),
    type: z.literal("dates"),
    variant: z.string()
});

export const moduleElettricitySupplySchema = z.object({
    output: outputServiceProvidersSchema,
    type: z.literal("elettricity_supply"),
    variant: z.string()
});

export const moduleEmploymentSchema = z.object({
    output: z.array(z.union([z.literal("EMPLOYEE"), z.literal("FREELANCER"), z.literal("RETIRED"), z.literal("STUDENT"), z.literal("UNEMPLOYED"), z.literal("HOMEMAKER")])).describe("cuf values of cuf employment"),
    type: z.literal("employment"),
    variant: z.string()
});

export const moduleGasSupplySchema = z.object({
    output: outputServiceProvidersSchema,
    type: z.literal("gas_supply"),
    variant: z.string()
});

export const moduleGenderSchema = z.object({
    output: outputModuleGenderSchema,
    type: z.literal("gender"),
    variant: z.string()
});

export const moduleGoalSchema = z.object({
    output: z.string(),
    type: z.literal("goal"),
    variant: z.string()
});

export const moduleHomeInternetSchema = z.object({
    output: outputServiceProvidersSchema,
    type: z.literal("home_internet"),
    variant: z.string()
});

export const moduleInstructionNoteSchema = z.object({
    output: z.string(),
    type: z.literal("instruction_note"),
    variant: z.string()
});

export const moduleLanguageSchema = z.object({
    output: z.string(),
    type: z.literal("language"),
    variant: z.string()
});

export const moduleLiteracySchema = z.object({
    output: outputModuleLiteracySchema,
    type: z.literal("literacy"),
    variant: z.string()
});

export const moduleLocalitySchema = z.object({
    output: outputModuleLocalitySchema,
    type: z.literal("locality"),
    variant: z.string()
});

export const moduleMobileInternetSchema = z.object({
    output: outputServiceProvidersSchema,
    type: z.literal("mobile_internet"),
    variant: z.string()
});

export const moduleOutOfScopeSchema = z.object({
    output: z.string(),
    type: z.literal("out_of_scope"),
    variant: z.string()
});

export const moduleSetupNoteSchema = z.object({
    output: z.string(),
    type: z.literal("setup_note"),
    variant: z.string()
});

export const moduleTargetSchema = z.object({
    output: z.number(),
    type: z.literal("target"),
    variant: z.string()
});

export const moduleTargetNoteSchema = z.object({
    output: z.string(),
    type: z.literal("target_note"),
    variant: z.string()
});

export const moduleTaskSchema = z.object({
    output: z.array(outputModuleTaskSchema),
    type: z.literal("tasks"),
    variant: z.string()
});

export const moduleTitleSchema = z.object({
    output: z.string(),
    type: z.literal("title"),
    variant: z.string()
});

export const moduleTouchpointsSchema = z.object({
    output: z.array(outputModuleTouchpointsSchema),
    type: z.literal("touchpoints"),
    variant: z.string()
});

export const moduleSchema = z.union([moduleTitleSchema, moduleDateSchema, moduleTaskSchema, moduleAgeSchema, moduleLanguageSchema, moduleLiteracySchema, moduleTargetSchema, moduleGoalSchema, moduleGenderSchema, moduleOutOfScopeSchema, moduleBrowserSchema, moduleTargetNoteSchema, moduleInstructionNoteSchema, moduleSetupNoteSchema, moduleTouchpointsSchema, moduleAdditionalTargetSchema, moduleEmploymentSchema, moduleLocalitySchema, moduleBankSchema, moduleElettricitySupplySchema, moduleMobileInternetSchema, moduleHomeInternetSchema, moduleGasSupplySchema, moduleAnnualIncomeRangeSchema]);

export const cpReqPlansSchema = z.object({
    campaign: z.object({
        id: z.number(),
        startDate: z.string(),
        title: z.string().describe("CustomerTitle ?? Title")
    }).optional(),
    config: z.object({
        modules: z.array(moduleSchema)
    }),
    from_template: z.object({
        id: z.number(),
        title: z.string()
    }).optional(),
    id: z.number(),
    price: z.string().optional(),
    project: z.object({
        id: z.number(),
        name: z.string()
    }),
    quote: z.object({
        id: z.number(),
        status: z.union([z.literal("pending"), z.literal("proposed"), z.literal("approved"), z.literal("rejected")]),
        value: z.string()
    }).optional(),
    status: planStatusSchema,
    workspace_id: z.number()
});
